### ISSUE TITLE
How to force to use custom bash.exe on Windows (without wsl)

### ISSUE THREAD

**Issue by gigi206** [rogalmic/vscode-bash-debug#122] opened 2019-12-16 20:39 UTC
##  Executables
```powershell
(Get-Command -ErrorAction "SilentlyContinue" bash).Path
C:\VSCode-Anywhere\apps\scoop\apps\msys2\current\usr\bin\bash.exe
```

```
$ where bash
C:\VSCode-Anywhere\apps\scoop\apps\git\2.24.1.windows.2\usr\bin\bash.exe
C:\VSCode-Anywhere\apps\scoop\apps\msys2\current\usr\bin\bash.exe
```

```
code --version
1.41.0
9579eda04fdb3a9bba2750f15193e5fafe16b959
x64
```

```
bash -c 'uname -a; for P in bash bashdb cat mkfifo pkill; do echo ---; which -a $P; command $P --version; done'
MINGW64_NT-10.0-18362 portable 3.0.7-338.x86_64 2019-07-11 10:58 UTC x86_64 Msys
---
/usr/bin/bash
GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
---
which: no bashdb in (/c/VSCode-Anywhere/apps/scoop/apps/python27/current/Scripts:/c/VSCode-Anywhere/apps/scoop/apps/python/current/Scripts:/c/VSCode-Anywhere/apps/saltstack:/mingw64/bin:/mingw32/bin:/usr/bin:/c/VSCode-Anywhere/apps/Chocolatey/bin:/c/VSCode-Anywhere/apps/scoop/shims:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Logiciels/Calibre2:/c/VSCode-Anywhere/apps/scoop/apps/python27/current/scripts:/c/VSCode-Anywhere/apps/scoop/apps/python/current:/c/VSCode-Anywhere/apps/scoop/apps/python/current/Scripts:/c/VSCode-Anywhere/apps/saltstack:/c/VSCode-Anywhere/apps/scoop/shims:/c/Users/gigi/Documents/anaconda3:/c/Users/gigi/Documents/anaconda3/Library/mingw-w64/bin:/c/Users/gigi/Documents/anaconda3/Library/usr/bin:/c/Users/gigi/Documents/anaconda3/Library/bin:/c/Users/gigi/Documents/anaconda3/Scripts:/c/VSCode-Anywhere/apps/Chocolatey/bin)
/usr/bin/bash: bashdb: command not found
---
/usr/bin/cat
cat (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Torbjorn Granlund and Richard M. Stallman.
---
/usr/bin/mkfifo
mkfifo (GNU coreutils) 8.31
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
---
which: no pkill in (/c/VSCode-Anywhere/apps/scoop/apps/python27/current/Scripts:/c/VSCode-Anywhere/apps/scoop/apps/python/current/Scripts:/c/VSCode-Anywhere/apps/saltstack:/mingw64/bin:/mingw32/bin:/usr/bin:/c/VSCode-Anywhere/apps/Chocolatey/bin:/c/VSCode-Anywhere/apps/scoop/shims:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/WINDOWS/System32/OpenSSH:/c/ProgramData/chocolatey/bin:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/Logiciels/Calibre2:/c/VSCode-Anywhere/apps/scoop/apps/python27/current/scripts:/c/VSCode-Anywhere/apps/scoop/apps/python/current:/c/VSCode-Anywhere/apps/scoop/apps/python/current/Scripts:/c/VSCode-Anywhere/apps/saltstack:/c/VSCode-Anywhere/apps/scoop/shims:/c/Users/gigi/Documents/anaconda3:/c/Users/gigi/Documents/anaconda3/Library/mingw-w64/bin:/c/Users/gigi/Documents/anaconda3/Library/usr/bin:/c/Users/gigi/Documents/anaconda3/Library/bin:/c/Users/gigi/Documents/anaconda3/Scripts:/c/VSCode-Anywhere/apps/Chocolatey/bin)
/usr/bin/bash: pkill: command not found
```

## Debug output
Paste here outputs in DEBUG CONSOLE (ctrl+shift+D or command+shift+D) with `"showDebugOutput": true` and `"trace": true` in `launch.json`.
Your `launch.json` may looks like:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}",
            "cwd": "${workspaceFolder}",
            "pathBash": "C:\\VSCode-Anywhere\\apps\\scoop\\apps\\git\\current\\bin\\bash.exe",
            "args": []
        }
    ]
}
```

## Details
Set **pathBash** not working result in error WSL bash

Is there a way not to use WSL and to use a custom bash? Like the bash.exe included in git or msys2

**Comment by rogalmic** [comment] 2019-12-17 10:20
Duplicate of #99 ...

**Closed by rogalmic** 2019-12-17 10:20 UTC
