### ISSUE TITLE
Debbuging does not start

### ISSUE THREAD

**Issue by Gt3pccb** [rogalmic/vscode-bash-debug#110] opened 2019-05-14 15:27 UTC
Issue Type: <b>Bug</b>

Installed Bash debug as per instructions and the scrolling blue bar nver stops rolling  and I get no co controll of the code.

Extension version: 0.3.4
VS Code version: Code 1.33.1 (51b0b28134d51361cf996d2f0a1c698247aeabd8, 2019-04-11T08:20:22.771Z)
OS version: Linux x64 3.10.0-957.10.1.el7.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7-8890 v3 @ 2.50GHz (32 x 2493)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.49GB (9.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by rogalmic** [comment] 2019-05-14 15:53
This is probably duplicate of :
https://github.com/rogalmic/vscode-bash-debug/issues/105

Please try setting debugConsole as terminalKind in launch.json (see referenced ticket). Fix is required in visual studio code itself, waiting for that...

**Comment by Gt3pccb** [comment] 2019-05-14 15:56
Mine is in Linux Centos and Redhat

**Comment by rogalmic** [comment] 2019-05-14 16:23
This issue affects all distros, basically terminalKind needs to be set..

**Closed** 2019-05-21 17:00 UTC
Labels: duplicate
