### ISSUE TITLE
debug hangs when using "terminalKind": "integrated"

### ISSUE THREAD

**Issue by tkumark** [rogalmic/vscode-bash-debug#135] opened 2020-04-20 16:08 UTC
I am using Ubuntu 18.04 with VSCode. When run with "terminalKind": "integrated" I get the following message. am I missing configuration

> bash -c "cd \"/home/kumar/DevWrkSpc/bashwrkspace\"\; while [[ ! -p \"/tmp/vscode-bash-debug-fifo-16621\" ]]\; do sleep 0.25\; done\; \"bash\" \"/home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/bashdb\" --quiet --tty \"/tmp/vscode-bash-debug-fifo-16621\" --tty_in \"/tmp/vscode-bash-debug-fifo-16621_in\" --library \"/home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir\" -- \"/home/kumar/DevWrkSpc/bashwrkspace/test.sh\" " 
> bash: line 0: cd: too many arguments
and it just hangs there.

I also tried with "terminalKind": "external" I am able to do debug but when it stops  I get the following message :

> bash: line 1: 27508 Killed                  bash /home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/bashdb --quiet --tty /tmp/vscode-bash-debug-fifo-14583 --tty_in /tmp/vscode-bash-debug-fifo-14583_in --library /home/kumar/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir -- /home/kumar/DevWrkSpc/bashwrkspace/test.sh

Is this expected or I need to do some thing else.

**Comment by rogalmic** [comment] 2020-04-20 16:24
Does terminal kind : "debugConsole" work?

**Comment by lantrix** [comment] 2020-04-24 11:54
I have same problem, although VSCode on Mac.

> Version: 1.44.2
> Commit: ff915844119ce9485abfe8aa9076ec76b5300ddd
> Date: 2020-04-16T17:07:18.473Z (1 wk ago)
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Darwin x64 19.3.0

With a configuration of:

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "bashdb",
      "request": "launch",
      "name": "Bash-Debug (simplest configuration)",
      "terminalKind": "integrated",
      "program": "${file}"
    }
  ]
}
```

which causes

```bash
bash-3.2$  bash -c "cd \"/Users/lantrix/repo/bastion-client\"\; while [[ ! -p \"/tmp/vscode-bash-debug-fifo-19219\" ]]\; do sleep 0.25\; done\; \"bash\" \"/Users/lantrix/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/bashdb\" --quiet --tty \"/tmp/vscode-bash-debug-fifo-19219\" --tty_in \"/tmp/vscode-bash-debug-fifo-19219_in\" --library \"/Users/lantrix/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir\" -- \"/Users/lantrix/repo/bastion-client/bastion-client.sh\" " 
bash: line 0: cd: too many arguments
```

As reqeusted, `"terminalKind": "debugConsole"` does work, with exit script details as shown, but I need to provide input for the script, so can't use the debug console.

```bash
"bash" "/Users/lantrix/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/bashdb" --quiet --tty "/tmp/vscode-bash-debug-fifo-15352" --tty_in "/tmp/vscode-bash-debug-fifo-15352_in" --library "/Users/lantrix/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir" -- "/Users/lantrix/repo/bastion-client/bastion-client.sh"
```

And lastly `"terminalKind": "external"` also works for me, launching the Mac Terminal, where I can give input.

It's only `"terminalKind": "integrated"` that causes the `bash: line 0: cd: too many arguments` issue.

**Comment by lantrix** [comment] 2020-04-24 12:15
Seems this may be the same issue as #133, at least for me - @tkumark doesn't seem to have escaped semicolons.

> The issue is that the command contains semicolons ";" , and newest VsCode seems to escape them "\;" in integrated terminal.

Removing the semicolons from the command that fails, and re-running it works for me. I'll follow #133 👏

**Comment by tkumark** [comment] 2020-04-25 15:30
@lantrix Where exactly do I have to remove the semicolon.

**Comment by lantrix** [comment] 2020-04-28 00:11
You need the semi colons. VSCode is escaping them in some cases as `\;` instead of `;` but I don't see that in your case or your output.

**Comment by Ortega-Dan** [comment] 2020-04-29 17:45
Having the very same issue ...
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "bashdb",
            "request": "launch",
            "name": "Bash-Debug (simplest configuration)",
            "program": "${file}",
            "terminalKind": "integrated"
        }
    ]
}

Output:
bash -c "cd \"/home/danort/toggleJava\"\; while [[ ! -p \"/tmp/vscode-bash-debug-fifo-11816\" ]]\; do sleep 0.25\; done\; \"bash\" \"/home/danort/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir/bashdb\" --quiet --tty \"/tmp/vscode-bash-debug-fifo-11816\" --tty_in \"/tmp/vscode-bash-debug-fifo-11816_in\" --library \"/home/danort/.vscode/extensions/rogalmic.bash-debug-0.3.7/bashdb_dir\" -- \"/home/danort/toggleJava/toggleJava.sh\" " 
bash: line 0: cd: too many arguments

**Comment by Ortega-Dan** [comment] 2020-04-29 18:04
This issue was related to vscode and they fixed it already ... and therefore it is working now on vscode insiders !!
![image](https://user-images.githubusercontent.com/24926168/80630409-cb6daf00-8a19-11ea-8833-dcda6ef375f1.png)
This was vscode fix: https://github.com/microsoft/vscode/issues/93166

**Comment by lantrix** [comment] 2020-05-02 09:17
So this is a duplicate of #133

**Comment by lantrix** [comment] 2020-05-13 11:05
This is fixed in VS Code 1.45.0 which is released now.

**Comment by Ortega-Dan** [comment] 2020-05-13 20:46
Yeap it is fixed on the release ... this issue can be closed now. @rogalmic

**Comment by rogalmic** [comment] 2020-05-14 04:19
Thanks for handling this. Closing..

**Closed by rogalmic** 2020-05-14 04:19 UTC
