### ISSUE TITLE
VS code crashes when script has syntax error or once execution completes

### ISSUE THREAD

**Issue by faizanahemad** [rogalmic/vscode-bash-debug#38] opened 2017-11-06 09:45 UTC
OS: MAC OSX 10.12.6
vs code version: Version 1.17.2 (1.17.2)

_launch.json_
```json
{
        "version": "0.2.0",
        "configurations": [
            
            {
                "name": "Bash-Debug (select script from list of sh files)",
                "type": "bashdb",
                "request": "launch",
                "scriptPath": "${command:SelectScriptName}",
                "commandLineArguments": "",
                "windows": {
                    "bashPath": "C:\\Windows\\sysnative\\bash.exe"
                },
                "linux": {
                    "bashPath": "bash"
                },
                "osx": {
                    "bashPath": "bash"
                }
            }
        ]
    }

```

Script used
```bash
#!/usr/bin/env bash
export NICE_VAR=10
export ANOTHER_VAR=20

for i in {0..25..5}
do
   export NICE_VAR=$((NICE_VAR + i))
   echo $NICE_VAR 
done

for ((i=1;i<=25;i+=1))
do
    export ANOTHER_VAR=$((ANOTHER_VAR+i))
    echo $ANOTHER_VAR
done

if [ $ANOTHER_VAR -gt $NICE_VAR ]
then
    echo "ANOTHER bigger than nice"
else
    echo "Nice is bigger or equal"
fi
```

Steps to reproduce. 
 - Directly run the script in debug mode, vs code exits after script finishes exec
 - Make a syntax error and run in debug mode, vs code crashes and exits

Script with errors

```bash
#!/usr/bin/env bash
export NICE_VAR=10
expor ANOTHER_VAR=20

for i {0..25..5}
do
   export NICE_VAR=$((NICE_VAR + i))
   echo $NICE_VAR 
done

for i in {0..25..5}
do
   export NICE_VAR=$((NICE_VAR + i))
   echo $NICE_VAR 
done

for ((i=1;i<=25;i+=1))
do
    export ANOTHER_VAR=$((ANOTHER_VAR+i))
    echo $ANOTHER_VAR
done

if [ $ANOTHER_VAR -gt $NICE_VAR ]
then
    echo "ANOTHER bigger than nice"
else
    echo "Nice is bigger or equal"
fi
```

**Comment by wataash** [comment] 2017-12-30 02:01
@faizanahemad 
Could you provide the output of following commands for me to guess the cause of the crash?

- `which -a pkill`
- `pkill -V`
- `brew info proctools`

I think your crash comes from a bug in `pkill` installed by homebrew. If so, you will get an output like:

```
$ which -a pkill
/usr/local/bin/pkill
/usr/bin/pkill

$ pkill -V
pkill (proctools 0.4pre1) http://proctools.sourceforge.net

$ brew info proctools
proctools: stable 0.4pre1 (bottled)
pgrep, pkill, and pfind for OpenBSD and Darwin (macOS)
https://proctools.sourceforge.io/
/usr/local/Cellar/proctools/0.4pre1 (9 files, 113.1KB) *
...
```

**Comment by wataash** [comment] 2018-03-09 12:41
I fixed the bug in `proctools` and sent [PR](https://sourceforge.net/p/proctools/bugs/1/), however,
 probably it will never be merged.

We'll fix it by avoiding using `/usr/local/bin/pkill` on macOS.

**Comment by wataash** [comment] 2018-03-13 13:34
Here's self explanatory gif.
![vscode-bash-debug_mac-pkill-crash](https://user-images.githubusercontent.com/4846670/37344701-739dca46-270e-11e8-833c-82915be57d3e.gif)

**Comment by rogalmic** [comment] 2018-03-17 19:23
Please verify with version 0.1.1 (just published).

**Comment by rogalmic** [comment] 2018-03-28 14:30
I think this is fixed, please re-open if needed...

**Closed by rogalmic** 2018-03-28 14:30 UTC
Labels: bug
